// <auto-generated />
using A3DET_CODE.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace A3DET_CODE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708182000_AddProfileImageUrlToUsers")]
    partial class AddProfileImageUrlToUsers
    {
    }
}
